-- Baseline des Schemas, wie Hibernate es bis einschliesslich Luna/33
-- mit ddl-auto=update selbst angelegt hat. Abgezogen per pg_dump aus einer
-- frischen postgres:16, gegen die die Anwendung einmal gestartet wurde -
-- nicht von Hand geschrieben, damit ddl-auto=validate danach durchlaeuft.
--
-- Die Constraint-Namen sind Hibernates generierte Hashes und bleiben genau
-- so stehen. Auf der Produktionsdatenbank existieren sie bereits unter
-- diesen Namen; wuerde man sie hier schoener schreiben, bekaeme eine frisch
-- migrierte Datenbank andere Namen als die per baselineOnMigrate
-- uebernommene Produktion - zwei Schemata, die sich langsam auseinander
-- entwickeln.

CREATE TABLE bank (
    id bigint NOT NULL,
    name character varying(255)
);
ALTER TABLE bank ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME bank_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE category (
    id bigint NOT NULL,
    name character varying(255)
);
ALTER TABLE category ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME category_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE income (
    id bigint NOT NULL,
    amount numeric(38,2),
    description character varying(255)
);
ALTER TABLE income ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME income_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE rule (
    id bigint NOT NULL,
    amount numeric(38,2),
    date_of_execution date NOT NULL,
    description character varying(255),
    is_change boolean,
    old_amount numeric(38,2),
    from_space_id bigint,
    to_space_id bigint
);
ALTER TABLE rule ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME rule_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE space (
    id bigint NOT NULL,
    name character varying(255)
);
ALTER TABLE space ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME space_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE spending (
    id bigint NOT NULL,
    amount numeric(38,2),
    description character varying(255),
    category_id bigint,
    rule_id bigint,
    transfer_id bigint
);
ALTER TABLE spending ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME spending_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE transfer (
    id bigint NOT NULL,
    amount numeric(38,2),
    date_of_execution date NOT NULL,
    description character varying(255),
    is_change boolean,
    old_amount numeric(38,2),
    from_bank_id bigint,
    to_bank_id bigint
);
ALTER TABLE transfer ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME transfer_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
ALTER TABLE ONLY bank
    ADD CONSTRAINT bank_pkey PRIMARY KEY (id);
ALTER TABLE ONLY category
    ADD CONSTRAINT category_pkey PRIMARY KEY (id);
ALTER TABLE ONLY income
    ADD CONSTRAINT income_pkey PRIMARY KEY (id);
ALTER TABLE ONLY rule
    ADD CONSTRAINT rule_pkey PRIMARY KEY (id);
ALTER TABLE ONLY space
    ADD CONSTRAINT space_pkey PRIMARY KEY (id);
ALTER TABLE ONLY spending
    ADD CONSTRAINT spending_pkey PRIMARY KEY (id);
ALTER TABLE ONLY transfer
    ADD CONSTRAINT transfer_pkey PRIMARY KEY (id);
ALTER TABLE ONLY spending
    ADD CONSTRAINT fk30aa9gp0mprj0msalprp6fcyn FOREIGN KEY (rule_id) REFERENCES rule(id);
ALTER TABLE ONLY spending
    ADD CONSTRAINT fk5hemivq8syl0juh94nubqussi FOREIGN KEY (transfer_id) REFERENCES transfer(id);
ALTER TABLE ONLY transfer
    ADD CONSTRAINT fkdiwqqahnnfmyibgjmcjj2c64u FOREIGN KEY (to_bank_id) REFERENCES bank(id);
ALTER TABLE ONLY rule
    ADD CONSTRAINT fke9kw38wjqm1sl2xulcq9kcoht FOREIGN KEY (to_space_id) REFERENCES space(id);
ALTER TABLE ONLY rule
    ADD CONSTRAINT fkeua43d47cgpom65x8wiej8rml FOREIGN KEY (from_space_id) REFERENCES space(id);
ALTER TABLE ONLY transfer
    ADD CONSTRAINT fknjbmamnlaxea14lb9v2h826rm FOREIGN KEY (from_bank_id) REFERENCES bank(id);
ALTER TABLE ONLY spending
    ADD CONSTRAINT fkrni0h7hy883wd1vadsju2kxta FOREIGN KEY (category_id) REFERENCES category(id);
