# Use postgres/example user/password credentials
# make two compose files, one for local testing and one for production
# use .env file for production
services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: example
      POSTGRES_DB: example
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - internal

  be:
    image: devp1337/myfinance:latest
    restart: always
    networks:
      - caddy
      - internal
    depends_on:
      - db

  fe:
    image: devp1337/myfinance:fe-latest
    restart: always
    networks:
      - caddy
    depends_on:
      - be

volumes:
  db_data:

networks:
  caddy:
    external: true
  internal:
    driver: bridge