services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data

  be:
    image: devp1337/myfinance:be-latest
    restart: always
    environment:
      DATABASE_URL: ${DATABASE_URL}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      APP_USER: ${APP_USER}
      APP_PASSWORD: ${APP_PASSWORD}
      SPRING_PROFILE: ${SPRING_PROFILE}
    depends_on:
      - db

  fe:
    image: devp1337/myfinance:fe-latest
    restart: always
    depends_on:
      - be

volumes:
  db_data: