services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - internal

  be:
    image: devp1337/myfinance:latest
    restart: always
    environment:
      DATABASE_URL: ${DATABASE_URL}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      APP_USER: ${APP_USER}
      APP_PASSWORD: ${APP_PASSWORD}
      SPRING_PROFILE: ${SPRING_PROFILE}
    networks:
      - caddy
      - internal
    depends_on:
      - db

  fe:
    image: devp1337/myfinance:fe-latest
    restart: always
    networks:
      - caddy
    depends_on:
      - be

volumes:
  db_data:

networks:
  caddy:
    external: true
  internal:
    driver: bridge