services:
  backup:
    image: devp1337/backup:2.0.0
    restart: always
    environment:
      TARGET_DOMAIN: ${ENV_TARGET_DOMAIN}
      TARGET_DOMAIN_USER: ${ENV_TARGET_DOMAIN_USER}
      SSH_PRIVATE_KEY_BASE64: ${ENV_SSH_PRIVATE_KEY_BASE64}
      RESTIC_REPOSITORY_NAME: ${ENV_RESTIC_REPOSITORY_NAME}
      RESTIC_PASSWORD: ${ENV_RESTIC_PASSWORD}
      PROVISION_MODE: ${ENV_PROVISION_MODE}
      POSTGRES_USER: ${ENV_POSTGRES_USER}
      POSTGRES_PASSWORD: ${ENV_POSTGRES_PASSWORD}
      POSTGRES_DATABASE: ${ENV_POSTGRES_DATABASE}
      POSTGRES_HOST: db
      TELEGRAM_TOKEN: ${ENV_TELEGRAM_TOKEN}
      TELEGRAM_CHAT_ID: ${ENV_TELEGRAM_CHAT_ID}
      CRON: ${ENV_CRON}
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -h db > /dev/null || exit 1" ]
      interval: 30s
      timeout: 20s
      retries: 3

  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    healthcheck:
      test: [
        "CMD-SHELL",
        "pg_isready -d ${DATABASE_NAME} -U ${DATABASE_USER} || exit 1"
      ]
      interval: 10s
      timeout: 5s
      retries: 5

  be:
    image: devp1337/myfinance:be-latest
    restart: always
    environment:
      DATABASE_URL: ${DATABASE_URL}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      APP_USER: ${APP_USER}
      APP_PASSWORD: ${APP_PASSWORD}
      SPRING_PROFILE: ${SPRING_PROFILE}
    depends_on:
      - db
    healthcheck:
      test: [
        "CMD-SHELL",
        "curl -u ${APP_USER}:${APP_PASSWORD} -s http://127.0.0.1:8080/actuator/health | grep '\"status\":\"UP\"' || exit 1"
      ]
      interval: 10s
      timeout: 20s
      retries: 3

  fe:
    image: devp1337/myfinance:fe-latest
    restart: always
    depends_on:
      - be
    healthcheck:
      test: [
        "CMD-SHELL",
        "wget -qO- http://127.0.0.1:80/ || exit 1"
      ]
      interval: 10s
      timeout: 20s
      retries: 3